"""
Django settings for django_siakad project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l(43&#xfu0%_kcmmx)x@#xgkt_j69evlz16ubfyxfkl6z^hrft'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    "unfold.contrib.filters",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_siakad',
    'master',
    'akademik',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_siakad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_siakad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_TITLE": "Sistem Informasi Akademik",
    "SITE_HEADER": "SIAKAD",
    "SITE_ICON": {    
        "light": lambda request: static("assets/logo-polisam.png"),  # light mode
        "dark": lambda request: static("assets/logo-polisam.png"),  # dark mode
    },
    # "SITE_LOGO": {
    #     "light": lambda request: static("assets/logo-polisam.png"),  # light mode
    #     "dark": lambda request: static("assets/logo-polisam.png"),  # dark mode
    # },
    # "SITE_SYMBOL": "school",  # symbol from icon set
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("assets/logo-polisam.png "),
        },
    ],
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": "Navigasi",
                "separator": True,
                "collapsible": True,
                "items": [
                     {
                        "title": "Dashboard",
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:index"),
                        # "badge": "new",
                        "permission": lambda request: request.user.is_superuser,
                    },
                ]
            },
            {
                "title": "Akademik",
                "separator": True,
                "collapsible": True,
                "items": [
                     {
                        "title": "Tahun Akademik",
                        "icon": "school",
                        "link": reverse_lazy("admin:akademik_tahunakademik_changelist"),
                    },
                    {
                        "title": "Mata Kuliah",
                        "icon": "checklist",
                        "link": reverse_lazy("admin:akademik_matakuliah_changelist"),
                    },
                    {
                        "title": "Jadwal",
                        "icon": "schedule",
                        "link": reverse_lazy("admin:akademik_jadwal_changelist"),
                    },
                    {
                        "title": "KRS",
                        "icon": "cast_for_education",
                        "link": reverse_lazy("admin:akademik_krs_changelist"),
                    },
                ]
            },
            {
                "title": "Master",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Prodi",
                        "icon": "school",
                        "link": reverse_lazy("admin:master_prodi_changelist"),
                    },
                    {
                        "title": "Ruang",
                        "icon": "room",
                        "link": reverse_lazy("admin:master_ruang_changelist"),
                    },
                    {
                        "title": "Dosen",
                        "icon": "person",
                        "link": reverse_lazy("admin:master_dosen_changelist"),
                    },
                    {
                        "title": "Mahasiswa",
                        "icon": "person",
                        "link": reverse_lazy("admin:master_mahasiswa_changelist"),
                    },                    
                ]
            },
            {
                "title": "Pengaturan",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Group",
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ]
            }            
        ]
    },

}