# Generated by Django 5.1.3 on 2024-12-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('kode', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'prodi',
                'verbose_name_plural': 'prodi',
                'indexes': [models.Index(fields=['nama'], name='master_prod_nama_cdc3ca_idx'), models.Index(fields=['kode'], name='master_prod_kode_a78922_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('kode', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'ruang',
                'verbose_name_plural': 'ruang',
                'indexes': [models.Index(fields=['nama'], name='master_ruan_nama_737405_idx'), models.Index(fields=['kode'], name='master_ruan_kode_cbd7c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('nim', models.CharField(max_length=15, null=True)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.prodi')),
            ],
            options={
                'verbose_name': 'mahasiswa',
                'verbose_name_plural': 'mahasiswa',
                'indexes': [models.Index(fields=['nama'], name='master_maha_nama_8fa52e_idx'), models.Index(fields=['nim'], name='master_maha_nim_6fb457_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('nid', models.CharField(max_length=15, null=True)),
                ('tgl_lahir', models.DateField(null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('l', 'Laki-laki'), ('p', 'perempuan')], max_length=1, null=True)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.prodi')),
            ],
            options={
                'verbose_name': 'dosen',
                'verbose_name_plural': 'dosen',
                'indexes': [models.Index(fields=['nama'], name='master_dose_nama_389eed_idx'), models.Index(fields=['nid'], name='master_dose_nid_66eb4d_idx')],
            },
        ),
    ]
